### ISSUE TITLE
Hid damage counter

### ISSUE THREAD

**Issue by Aborts** [0anth/damage-counter#1]
could we get an option to not display the counter when we arent in combat /  after a set amount of time? " make this customisable if possible"

**Comment by 0anth** [comment]
Added option to automatically hide overlay when boss dies in commit 07657a1ae9feb9a2ffdc325ac4717d400b3b245d.

**Comment by 0anth** [comment]
Created pull request https://github.com/runelite/plugin-hub/pull/742
